import 'normalize.css'
import '../pages/index/index.scss'
import '../pages/index/index-mobile.scss'
import '../pages/index/index'
import '../components/head/fullpage/jquery.fullPage.css'
import 'animate.css'